sonar.projectKey=Unified-Code-Coverage
sonar.projectName=Unified-Code-Coverage
sonar.sourceEncoding=UTF-8

# Sources
sonar.sources=java-project/src/main,cpp-project
sonar.tests=java-project/src/test

# Java binaries
sonar.java.binaries=java-project/target/classes

# Java coverage
sonar.coverage.jacoco.xmlReportPaths=java-project/target/site/jacoco/jacoco.xml

# C++ gcov coverage
sonar.cfamily.gcov.reportsPath=cpp-project

# Threads
sonar.cfamily.threads=2
