import xml.etree.ElementTree as ET
import json
import os

def parse_jacoco(xml_path):
    """Parses Java JaCoCo XML for deep metrics"""
    if not os.path.exists(xml_path): return {"error": "Java XML missing"}
    tree = ET.parse(xml_path)
    root = tree.getroot()
    data = {"classes": [], "totals": {}}
    for counter in root.findall('counter'):
        data["totals"][counter.get('type')] = {
            "missed": counter.get('missed'),
            "covered": counter.get('covered')
        }
    for pkg in root.findall('package'):
        for cls in pkg.findall('class'):
            data["classes"].append({
                "name": cls.get('name'),
                "lines_missed": cls.find("counter[@type='LINE']").get('missed') if cls.find("counter[@type='LINE']") is not None else "0"
            })
    return data

def parse_gcovr(xml_path):
    """Parses C++ Gcovr XML (Cobertura format)"""
    if not os.path.exists(xml_path): return {"error": "C++ XML missing"}
    tree = ET.parse(xml_path)
    root = tree.getroot()
    return {
        "line_rate": root.get('line-rate'),
        "branch_rate": root.get('branch-rate'),
        "lines_covered": root.get('lines-covered'),
        "lines_valid": root.get('lines-valid')
    }

def main():
    final_report = {
        "metadata": {"status": "Success", "version": "2.0"},
        "java_detailed": parse_jacoco("java-project/target/site/jacoco/jacoco.xml"),
        "cpp_detailed": parse_gcovr("cpp-project/sonar-cpp-coverage.xml"),
        "sonar_cloud_analysis": {},
        "issues_and_bugs": {}
    }

    # Load the JSONs generated by your curl commands
    if os.path.exists("sonar_metrics.json"):
        with open("sonar_metrics.json", "r") as f:
            final_report["sonar_cloud_analysis"] = json.load(f)
            
    if os.path.exists("sonar_detailed_issues.json"):
        with open("sonar_detailed_issues.json", "r") as f:
            final_report["issues_and_bugs"] = json.load(f)

    with open("unified_full_report.json", "w") as f:
        json.dump(final_report, f, indent=4)
    print("--- Unified Report Created: unified_full_report.json ---")

if __name__ == "__main__":
    main()
